"use client";

import { useState } from "react";
import Button from "@/components/ui/Button";
import ArchitecturalPlanView from "@/components/ui/ArchitecturalPlanView";
import type { ArchitecturalPlan } from "@/lib/architecturalPlan";

const SPECIAL_ROOM_OPTIONS: { value: string; label: string; requiresMultiFloor?: boolean }[] = [
  { value: "office", label: "Home Office" },
  { value: "pooja", label: "Pooja Room" },
  { value: "study", label: "Study Room" },
  { value: "theater", label: "Home Theater" },
  { value: "gym", label: "Gym" },
  { value: "servant", label: "Servant Room" },
  { value: "store", label: "Store Room" },
  { value: "lift", label: "Lift", requiresMultiFloor: true },
];

const AESTHETIC_OPTIONS = ["Sleek & Minimal", "Warm & Traditional", "Bold & Premium"];

type FormState = {
  fullName: string;
  email: string;
  plotWidth: string;
  plotDepth: string;
  roadSide: "north" | "south" | "east" | "west";
  roadWidth: string;
  floors: string;
  bedrooms: string;
  bathrooms: string;
  parkingSpaces: string;
  wantsBalcony: boolean;
  wantsTerrace: boolean;
  staircaseType: "straight" | "dogleg" | "spiral";
  specialRooms: string[];
  vastu: boolean;
  aesthetic: string;
  budget: string;
  preferences: string;
};

const initialState: FormState = {
  fullName: "",
  email: "",
  plotWidth: "30",
  plotDepth: "45",
  roadSide: "south",
  roadWidth: "30",
  floors: "2",
  bedrooms: "3",
  bathrooms: "3",
  parkingSpaces: "1",
  wantsBalcony: true,
  wantsTerrace: false,
  staircaseType: "dogleg",
  specialRooms: [],
  vastu: false,
  aesthetic: AESTHETIC_OPTIONS[0],
  budget: "",
  preferences: "",
};

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div>
      <label className="block font-inter text-sm font-medium text-charcoal mb-1">{label}</label>
      {children}
    </div>
  );
}

const inputClass =
  "w-full border border-sand rounded-lg px-4 py-2.5 font-inter text-sm focus:outline-none focus:border-warm-brown bg-cream";

export default function DetailedDesignPage() {
  const [form, setForm] = useState<FormState>(initialState);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [plan, setPlan] = useState<ArchitecturalPlan | null>(null);

  const floorsNum = Number(form.floors) || 1;

  const toggleSpecialRoom = (value: string) => {
    setForm((f) => ({
      ...f,
      specialRooms: f.specialRooms.includes(value)
        ? f.specialRooms.filter((r) => r !== value)
        : [...f.specialRooms, value],
    }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (loading) return;
    setLoading(true);
    setError("");
    setPlan(null);

    try {
      const res = await fetch("/api/design/detailed", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          fullName: form.fullName.trim(),
          email: form.email.trim(),
          plotWidth: Number(form.plotWidth),
          plotDepth: Number(form.plotDepth),
          roadSide: form.roadSide,
          roadWidth: Number(form.roadWidth),
          floors: Number(form.floors),
          bedrooms: Number(form.bedrooms),
          bathrooms: Number(form.bathrooms),
          parkingSpaces: Number(form.parkingSpaces),
          wantsBalcony: form.wantsBalcony,
          wantsTerrace: form.wantsTerrace,
          staircaseType: floorsNum > 1 ? form.staircaseType : "none",
          specialRooms: form.specialRooms,
          vastu: form.vastu,
          aesthetic: form.aesthetic,
          budget: form.budget ? Number(form.budget) : undefined,
          preferences: form.preferences.trim(),
        }),
      });
      const result = await res.json();
      if (result.success) {
        setPlan(result.plan);
      } else {
        setError(result.error || "Couldn't generate the detailed plan right now.");
      }
    } catch {
      setError("Something went wrong. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <main className="bg-sand min-h-screen py-16">
      <div className="max-w-3xl mx-auto px-4">
        <h1 className="font-playfair text-3xl font-bold text-charcoal mb-2 text-center">
          Detailed Architectural Concept Plan
        </h1>
        <p className="font-inter text-sm text-muted text-center mb-8">
          Tell us about your plot and requirements for a deeper, multi-floor concept plan with a site plan, area
          schedule, and door/window schedule — generated by AI for early design discussion, not for construction.
        </p>

        <form onSubmit={handleSubmit} className="flex flex-col gap-6">
          <div className="bg-ivory rounded-2xl p-6 shadow-lg border border-sand flex flex-col gap-4">
            <h3 className="font-playfair text-lg font-bold text-charcoal">Plot & Site</h3>
            <div className="grid grid-cols-2 gap-4">
              <Field label="Plot width (ft)">
                <input
                  type="number"
                  min={15}
                  className={inputClass}
                  value={form.plotWidth}
                  onChange={(e) => setForm({ ...form, plotWidth: e.target.value })}
                  required
                />
              </Field>
              <Field label="Plot depth (ft)">
                <input
                  type="number"
                  min={15}
                  className={inputClass}
                  value={form.plotDepth}
                  onChange={(e) => setForm({ ...form, plotDepth: e.target.value })}
                  required
                />
              </Field>
              <Field label="Road side (facing)">
                <select
                  className={inputClass}
                  value={form.roadSide}
                  onChange={(e) => setForm({ ...form, roadSide: e.target.value as FormState["roadSide"] })}
                >
                  <option value="north">North</option>
                  <option value="south">South</option>
                  <option value="east">East</option>
                  <option value="west">West</option>
                </select>
              </Field>
              <Field label="Road width (ft)">
                <input
                  type="number"
                  min={10}
                  className={inputClass}
                  value={form.roadWidth}
                  onChange={(e) => setForm({ ...form, roadWidth: e.target.value })}
                />
              </Field>
            </div>
          </div>

          <div className="bg-ivory rounded-2xl p-6 shadow-lg border border-sand flex flex-col gap-4">
            <h3 className="font-playfair text-lg font-bold text-charcoal">Building</h3>
            <div className="grid grid-cols-2 gap-4">
              <Field label="Number of floors">
                <select className={inputClass} value={form.floors} onChange={(e) => setForm({ ...form, floors: e.target.value })}>
                  <option value="1">1 (Single storey)</option>
                  <option value="2">2</option>
                  <option value="3">3</option>
                  <option value="4">4</option>
                </select>
              </Field>
              <Field label="Parking spaces">
                <input
                  type="number"
                  min={0}
                  max={4}
                  className={inputClass}
                  value={form.parkingSpaces}
                  onChange={(e) => setForm({ ...form, parkingSpaces: e.target.value })}
                />
              </Field>
              <Field label="Bedrooms (total)">
                <input
                  type="number"
                  min={1}
                  className={inputClass}
                  value={form.bedrooms}
                  onChange={(e) => setForm({ ...form, bedrooms: e.target.value })}
                />
              </Field>
              <Field label="Bathrooms (total)">
                <input
                  type="number"
                  min={1}
                  className={inputClass}
                  value={form.bathrooms}
                  onChange={(e) => setForm({ ...form, bathrooms: e.target.value })}
                />
              </Field>
              {floorsNum > 1 && (
                <Field label="Staircase style">
                  <select
                    className={inputClass}
                    value={form.staircaseType}
                    onChange={(e) => setForm({ ...form, staircaseType: e.target.value as FormState["staircaseType"] })}
                  >
                    <option value="straight">Straight</option>
                    <option value="dogleg">Dog-legged</option>
                    <option value="spiral">Spiral</option>
                  </select>
                </Field>
              )}
              <Field label="Design aesthetic">
                <select className={inputClass} value={form.aesthetic} onChange={(e) => setForm({ ...form, aesthetic: e.target.value })}>
                  {AESTHETIC_OPTIONS.map((a) => (
                    <option key={a} value={a}>
                      {a}
                    </option>
                  ))}
                </select>
              </Field>
            </div>
            <div className="flex gap-6">
              <label className="flex items-center gap-2 font-inter text-sm text-charcoal">
                <input type="checkbox" checked={form.wantsBalcony} onChange={(e) => setForm({ ...form, wantsBalcony: e.target.checked })} />
                Balcony
              </label>
              <label className="flex items-center gap-2 font-inter text-sm text-charcoal">
                <input type="checkbox" checked={form.wantsTerrace} onChange={(e) => setForm({ ...form, wantsTerrace: e.target.checked })} />
                Terrace (top floor)
              </label>
            </div>
          </div>

          <div className="bg-ivory rounded-2xl p-6 shadow-lg border border-sand flex flex-col gap-4">
            <h3 className="font-playfair text-lg font-bold text-charcoal">Special Requirements</h3>
            <div className="grid grid-cols-2 gap-2">
              {SPECIAL_ROOM_OPTIONS.filter((o) => !o.requiresMultiFloor || floorsNum > 1).map((opt) => (
                <label key={opt.value} className="flex items-center gap-2 font-inter text-sm text-charcoal">
                  <input
                    type="checkbox"
                    checked={form.specialRooms.includes(opt.value)}
                    onChange={() => toggleSpecialRoom(opt.value)}
                  />
                  {opt.label}
                </label>
              ))}
            </div>
            <label className="flex items-center gap-2 font-inter text-sm text-charcoal">
              <input type="checkbox" checked={form.vastu} onChange={(e) => setForm({ ...form, vastu: e.target.checked })} />
              Follow Vastu guidelines where possible
            </label>
            <Field label="Budget (optional, in ₹)">
              <input
                type="number"
                min={0}
                className={inputClass}
                value={form.budget}
                onChange={(e) => setForm({ ...form, budget: e.target.value })}
              />
            </Field>
            <Field label="Mandatory preferences (optional)">
              <textarea
                className={inputClass}
                rows={3}
                placeholder="e.g. attached bathroom for every bedroom, open kitchen, east-facing master bedroom..."
                value={form.preferences}
                onChange={(e) => setForm({ ...form, preferences: e.target.value })}
              />
            </Field>
          </div>

          <div className="bg-ivory rounded-2xl p-6 shadow-lg border border-sand flex flex-col gap-4">
            <h3 className="font-playfair text-lg font-bold text-charcoal">Contact</h3>
            <div className="grid grid-cols-2 gap-4">
              <Field label="Full name">
                <input
                  type="text"
                  className={inputClass}
                  value={form.fullName}
                  onChange={(e) => setForm({ ...form, fullName: e.target.value })}
                />
              </Field>
              <Field label="Email">
                <input
                  type="email"
                  className={inputClass}
                  value={form.email}
                  onChange={(e) => setForm({ ...form, email: e.target.value })}
                  required
                />
              </Field>
            </div>
          </div>

          <Button type="submit" disabled={loading} className="self-center px-10">
            {loading ? "Generating your concept plan…" : "Generate Detailed Plan"}
          </Button>
        </form>

        {error && <p className="font-inter text-sm text-terracotta mt-6 text-center">{error}</p>}

        {plan && (
          <div className="mt-10">
            <ArchitecturalPlanView plan={plan} />
          </div>
        )}
      </div>
    </main>
  );
}
